version: "2"
services:
  geth-bootnode:
    hostname: geth-bootnode
    environment:
      - nodekeyhex=3be27887153ab7e7678219842e405671869c5ff46a9639596148b8f44c4c234a
    build:
      context: ./bootnode
    ports:
      - 30318:30318/udp
